export default
[
    {   
        name: "React Sneakers",
        author: "Гильманов Наиль",
        description: "Современный магазин кроссовок. Этот пет проект был сделан для изучения основ React и Redux.",
        image: "react_sneakers.png",
        link: "https://nailgilmanov.github.io/react-sneakers/#/",
        tags: ["html", "css", "react"],
    },
    {
        name: "PracticeHub",
        author: "Лобков Антон",
        description: "Один из наших готовых проектов - сайт с курсами, где их можно создавать и проходить, а так же добавлять домашние задания.",
        image: "practicehub.jpg",
        link: "https://github.com/tizerr/PracticeHub",
        tags: ["html", "css", "flask"],
    },
    {
        name: "Rock, scissors, paper",
        author: "Галеев Руслан",
        description: "Браузерная игра “Камень, ножницы, бумага”, выполненная на PyScript. Есть также и на мобильных телефонах.",
        image: "rsp.png",
        link: "https://stonescissorspaper-pyscript.grusl.repl.co/",
        tags: ["pyscript"],
    },
    {
        name: "Сайт металлобазы",
        author: "Моисеева Софья",
        description: "Маркетинговый информационный сайт Металлобазы Лазаревской, был выполнен на чистых HTML и CSS, по техническому заданию заказчика.",
        image: "metalbase.png",
        link: "https://seelssocute.ru/",
        tags: ["html", "css"],
    },
    {
        name: "Moby",
        author: "Гильманов Наиль",
        description: "Мобильная онлайн афиша с удобным интерфейсом в виде карты. Использовался YandexMapsApi.",
        image: "moby.jpg",
        link: "https://github.com/asasss3233/moby",
        tags: ["flask", "html", "css", "javascript"],
    },
    {
        name: "MORE WILD",
        author: "Моисеева Софья",
        description: "Дизайн трендового интернет-магазина MORE WILD.",
        image: "more_wild.png",
        link: "https://www.figma.com/file/Qw2vWJEScu0TmihJDWXgTy/MORE-WILD-%D0%BF%D0%BE%D0%BB%D0%BD%D1%8B%D0%B9-%D1%81%D0%B0%D0%B9%D1%82?node-id=0%3A1&t=7GIfkXxuJhlQ23ms-1",
        tags: ["figma"],
    },
    {
        name: "FTest",
        author: "Галеев Руслан",
        description: "Сервис по заучиванию того, что нужно просто запомнить.",
        image: "ftest.png",
        link: "",
        tags: ["django"],
    },
    {
        name: "Профитроль",
        author: "Моисеева Софья",
        description: "Дизайн-проект кофейни “Профитроль”. Был выполнен в Figma, является одним из самых первых проектов.",
        image: "profitrol.png",
        link: "https://www.figma.com/file/dk2MpM8OaqXlupsBmrLt7y/%D0%BA%D0%BE%D1%84%D0%B5%D0%B9%D0%BD%D1%8F-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D1%82%D1%80%D0%BE%D0%BB%D1%8C?node-id=0%3A1&t=VfyF2ZSnHOAcaM6V-1",
        tags: ["figma"],
    },
    {
        name: "\"Пастораль\"",
        author: "Моисеева Софья",
        description: "Дизайн интернет-магазина цветов “Пастораль”. Является одним из самых первых проектов. В скором времени планирует ре-дизайн.",
        image: "pastoral.png",
        link: "https://www.figma.com/file/1pMTGWJXt8iB5Shhluft0b/%D0%BF%D0%B0%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BB%D1%8C?node-id=0%3A1&t=yQd377Rvm99YLkQL-1",
        tags: ["figma"],
    },
    {
        name: "MMO API",
        author: "Галеев Руслан",
        description: "API-сервис интернет-маркета.",
        image: "mmo_api.png",
        link: "",
        tags: ["fastapi"],
    },
    {
        name: "FullDec",
        author: "Галеев Руслан",
        description: "Сервис для заучивания имен авторов произведений (для ИС).",
        image: "fulldec.png",
        link: "",
        tags: ["django"],
    },
    {
        name: "LibAni",
        author: "Галеев Руслан",
        description: "Самописный аналог сайта Shikimori, который является энциклопедией аниме и манги.",
        image: "libani.png",
        link: "",
        tags: ["django"],
    }
]